#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED


char lettresAEssayer[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";


const auto MOT1{"HEXAKOSIOIHEXEKONTAHEXAPHOBIE"};
const auto MOT2{"HIPPOPOMONSTROSESQUIPPEDALIOPHOBIE"};
const auto MOT3{"DICTIONNAIRE"};
const auto MOT4{"UNMOTSUPERLONG"};


#endif // CONSTANTES_H_INCLUDED
